// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0
// source: companies.sql

package dbs

import (
	"context"
	"time"
)

const companyNewAndGetID = `-- name: CompanyNewAndGetID :one
INSERT INTO companies (alias, name, created_by, created_at)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type CompanyNewAndGetIDParams struct {
	Alias     string
	Name      string
	CreatedBy int64
	CreatedAt time.Time
}

func (q *Queries) CompanyNewAndGetID(ctx context.Context, arg CompanyNewAndGetIDParams) (int64, error) {
	row := q.queryRow(ctx, q.companyNewAndGetIDStmt, companyNewAndGetID,
		arg.Alias,
		arg.Name,
		arg.CreatedBy,
		arg.CreatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
