// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0

package dbs

import (
	"database/sql"
	"time"
)

type Company struct {
	ID        int64
	Alias     string
	Name      string
	CreatedBy int64
	CreatedAt time.Time
}

type Review struct {
	ID        int64
	ParentID  sql.NullInt64
	CompanyID int64
	Content   string
	CreatedBy int64
	CreatedAt time.Time
}

type User struct {
	ID        int64
	Name      string
	CreatedAt time.Time
}

type Vacancy struct {
	ID        int64
	CompanyID int64
	Title     string
	CreatedBy int64
	CreatedAt time.Time
}
